---
DISABLE:
  - COPYPASTE
  - SPELL

DISABLE_LINTERS:
  - JSON_NPM_PACKAGE_JSON_LINT
  - PHP_PSALM
  - REPOSITORY_DEVSKIM

REPOSITORY_CHECKOV_ARGUMENTS: "--skip-path 'vendor/*'"

PHP_PHPSTAN_PRE_COMMANDS:
  - command: composer install --no-interaction --no-progress
    cwd: workspace

PHP_PHPCS_COMMAND_REMOVE_ARGUMENTS: "--standard=/action/lib/.automation/phpcs.xml"
PHP_PHPCS_ARGUMENTS: "--standard=Drupal,DrupalPractice"
