DISABLE: COPYPASTE,SPELL
ADDITIONAL_EXCLUDED_DIRECTORIES: "vendor"

REPOSITORY_CHECKOV_ARGUMENTS: "--skip-path 'vendor/*'"

PHP_PHPSTAN_PRE_COMMANDS:
  - command: composer install --no-interaction --no-progress
    cwd: workspace
