---
name: PHP

on:
  push:
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: "8.2"
          extensions: gd
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run phpcs
        run: vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme --ignore=vendor/,core/ --warning-severity=0 .

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: "8.2"
          extensions: gd
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run phpstan
        run: vendor/bin/phpstan analyse --no-progress
